openapi: "3.1.0"
info:
  title: "TI-Messenger/Fachdienst/Registrierungsdienst/Invite-Permission"
  version: ${project.version}
  description: "Diese API wird vom Messenger-Proxy konsumiert (Berechtigungsstufe 2)."

servers:
  - url: "http://localhost:8080"
    description: "Lokale Entwicklungsmaschine"

paths:
  /vzd/invite:
    post:
      description: "Holt invite permission f체r Berechtigungsstufe 3 f체r zwei User"
      operationId: getUserPublicityFromVZD
      tags:
        - InvitePermission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InvitePermissionDto"
      responses:
        '200':
          description: "Antwort falls zul채ssig"
        '403':
          description: "Antwort falls nicht zul채ssig"

components:
  schemas:
    InvitePermissionDto:
      type: object
      required:
        - invitingUser
        - invitedUser
      properties:
        invitingUser:
          type: string
        invitedUser:
          type: string
