apiVersion: v1
kind: Service
metadata:
  name: {{ include "registration-service.fullname" . }}-backend
  labels:
    {{- include "registration-service.labels" . | nindent 4 }}
    app.kubernetes.io/app: registration-service-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: backend-http
      protocol: TCP
      name: backend-http
    - port: {{ .Values.backend.healthService.port }}
      targetPort: health
      protocol: TCP
      name: backend-http-health
  selector:
    {{- include "registration-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/app: registration-service-backend
