{{- if .Values.ingress.enabled -}}
{{- $fullName := include "registration-service.fullname" . -}}
{{- $svcPort := .Values.frontend.service.port -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-frontend
  labels:
    {{- include "registration-service.labels" . | nindent 4 }}
    app.kubernetes.io/app: {{ $fullName }}-frontend
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.frontend.hostName }}.{{ .Values.fqdn }}
      secretName: tls-frontend-general
  rules:
  - host: {{ .Values.frontend.hostName }}.{{ .Values.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-frontend
            port:
              number: {{ .Values.frontend.service.port }}
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}-backend
            port:
              number: {{ .Values.backend.service.port }}
      - path: /backend/federation
        pathType: Prefix
        backend:
          service:
            name: does-not-exist
            port:
              number: 80
      - path: /backend/vzd/invite
        pathType: Prefix
        backend:
          service:
            name: does-not-exist
            port:
              number: 80
{{- end }}
