{{- $fullName := include "registration-service.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-frontend"
  labels:
    {{- include "registration-service.labels" . | nindent 4 }}
    app.kubernetes.io/app: {{ $fullName }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "registration-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/app: {{ $fullName }}-frontend
  template:
    metadata:
      {{- if .Values.rollMe.enabled }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "registration-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/app: {{ $fullName }}-frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "registration-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: API_URL
              value: "https://{{ .Values.frontend.hostName }}.{{ .Values.fqdn }}"
            - name: KEYCLOAK_URL
              value: "https://{{ .Values.keycloak.hostName }}.{{ .Values.fqdn }}"
            - name: REDIRECT_URI
              value: "https://{{ .Values.frontend.hostName }}.{{ .Values.fqdn }}"
            - name: ORG_ADMIN_URI
              value: "https://{{ .Values.frontend.orgAdminHostName }}.{{ .Values.fqdn }}"
            - name: FACHDIENST_META_URL
              value: "https://{{ .Values.frontend.fachdienstMetaHostName }}.{{ .Values.fqdn }}"
          ports:
            - name: frontend-http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: frontend-http
          readinessProbe:
            httpGet:
              path: /
              port: frontend-http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx/
            - name: nginx-pid
              mountPath: /var/run
            - name: runtimeconfig
              mountPath: /usr/share/nginx/config/runtimeconfig.json
              subPath: runtimeconfig.json
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-cache
          emptyDir:
            sizeLimit: 10Mi
        - name: nginx-pid
          emptyDir:
            sizeLimit: 10Mi
        - name: runtimeconfig
          configMap:
            name: frontend-{{ $fullName }}-runtimecfg
            items:
              - key: runtimeconfig.json
                path: runtimeconfig.json
        - name: nginx-conf
          configMap:
            name: frontend-{{ $fullName }}-nginx
            items:
              - key: default.conf
                path: default.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
