{{- $fullName := include "registration-service.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-keycloak
  labels:
    {{- include "registration-service.labels" . | nindent 4 }}
    app.kubernetes.io/app: {{ $fullName }}-keycloak
spec:
  ports:
  - name: {{ $fullName }}-keycloak
    port: 8080
    targetPort: keycloak
  selector:
    {{- include "registration-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/app: {{ $fullName }}-keycloak
  type: ClusterIP