### RS256
POST https://auth-{{env}}.vzd.ti-dienste.de:9443/auth/realms/TI-Provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=client_credentials

// Saving the access token
> {%
    client.global.set("accessToken", response.body.access_token);
%}

### BP256R1
GET https://fhir-directory-{{env}}.vzd.ti-dienste.de/ti-provider-authenticate
Authorization: Bearer {{accessToken}}

// Saving the access token
> {%
    client.global.set("providerServicesToken", response.body.access_token);
%}

### Documentation for the following requests: https://github.com/gematik/api-vzd/blob/main/src/openapi/I_VZD_TIM_Provider_Services.yaml

### Get role of matrix user ('none', 'pract', 'org', 'orgPract')
GET https://fhir-directory-{{env}}.vzd.ti-dienste.de/tim-provider-services/localization?mxid=matrix:u/example:test.example.com
Authorization: Bearer {{providerServicesToken}}

### Add domain to federation list
POST https://fhir-directory-{{env}}.vzd.ti-dienste.de/tim-provider-services/federation
Authorization: Bearer {{providerServicesToken}}
Content-Type: application/json

{
"domain": "test.example.com",
"isInsurance": false,
"telematikID": "test"
}

### Delete domain from federation list
DELETE https://fhir-directory-{{env}}.vzd.ti-dienste.de/tim-provider-services/federation/test.example.com
Authorization: Bearer {{providerServicesToken}}


### Get federation list from VZD (BP256R1)
GET https://fhir-directory-{{env}}.vzd.ti-dienste.de/tim-provider-services/FederationList/federationList.jws
Authorization: Bearer {{providerServicesToken}}

### Find Healthcare service for telematikID
GET https://fhir-directory-{{env}}.vzd.ti-dienste.de/search/HealthcareService?identifier=1111-akq
Authorization: Bearer {{providerServicesToken}}